-- Add comprehensive book categories
-- Migration: 20260416010400_add_comprehensive_categories.sql

INSERT INTO public.categories (name, slug) VALUES
-- 1) Fiksi (Fiction)
('Fiksi', 'fiksi'),
('Fantasi', 'fantasi'),
('Fantasi epik', 'fantasi-epik'),
('Fantasi urban', 'fantasi-urban'),
('Fantasi gelap', 'fantasi-gelap'),
('Sains fiksi', 'sains-fiksi'),
('Distopia', 'distopia'),
('Pasca-apokaliptik', 'pasca-apokaliptik'),
('Petualangan', 'petualangan'),
('Aksi', 'aksi'),
('Misteri', 'misteri'),
('Detektif', 'detektif'),
('Thriller', 'thriller'),
('Psychological thriller', 'psychological-thriller'),
('Horor', 'horor'),
('Gothic', 'gothic'),
('Romance', 'romance'),
('Contemporary romance', 'contemporary-romance'),
('Historical romance', 'historical-romance'),
('Comedy romance', 'comedy-romance'),
('Drama', 'drama'),
('Slice of life', 'slice-of-life'),
('Literary fiction', 'literary-fiction'),
('Realism', 'realism'),
('Magical realism', 'magical-realism'),
('Satire', 'satire'),
('Parodi', 'parodi'),
('Fable', 'fable'),
('Fairy tale', 'fairy-tale'),
('Mythology retelling', 'mythology-retelling'),
('Adventure fiction', 'adventure-fiction'),
('War fiction', 'war-fiction'),
('Crime fiction', 'crime-fiction'),
('Speculative fiction', 'speculative-fiction'),
('Supernatural fiction', 'supernatural-fiction'),
('Suspense', 'suspense'),
('Tragedi', 'tragedi'),
('Epic', 'epic'),
('Coming-of-age', 'coming-of-age'),

-- 2) Nonfiksi (Non-Fiction)
('Nonfiksi', 'nonfiksi'),
('Biografi', 'biografi'),
('Autobiografi', 'autobiografi'),
('Memoar', 'memoar'),
('Esai', 'esai'),
('Jurnalistik', 'jurnalistik'),
('Sejarah', 'sejarah'),
('Buku politik', 'buku-politik'),
('Buku sosial', 'buku-sosial'),
('Buku budaya', 'buku-budaya'),
('Buku ekonomi', 'buku-ekonomi'),
('Buku bisnis', 'buku-bisnis'),
('Buku manajemen', 'buku-manajemen'),
('Buku motivasi', 'buku-motivasi'),
('Pengembangan diri', 'pengembangan-diri'),
('Psikologi', 'psikologi'),
('Sosiologi', 'sosiologi'),
('Filsafat', 'filsafat'),
('Pendidikan', 'pendidikan'),
('Kesehatan', 'kesehatan'),
('Kebugaran', 'kebugaran'),
('Diet dan nutrisi', 'diet-dan-nutrisi'),
('Parenting', 'parenting'),
('Hubungan', 'hubungan'),
('Keuangan pribadi', 'keuangan-pribadi'),
('Investasi', 'investasi'),
('Kewirausahaan', 'kewirausahaan'),
('Kepemimpinan', 'kepemimpinan'),
('Produktivitas', 'produktivitas'),
('Komunikasi', 'komunikasi'),
('Public speaking', 'public-speaking'),
('Keterampilan hidup', 'keterampilan-hidup'),
('Travel', 'travel'),
('Kuliner', 'kuliner'),
('Seni dan desain', 'seni-dan-desain'),
('Fotografi', 'fotografi'),
('Teknologi', 'teknologi'),
('Komputer', 'komputer'),
('Internet', 'internet'),
('Teknik', 'teknik'),
('Sains populer', 'sains-populer'),
('Alam', 'alam'),
('Lingkungan', 'lingkungan'),
('Hewan', 'hewan'),
('Politik', 'politik'),
('Hukum', 'hukum'),
('Agama', 'agama'),
('Spiritualitas', 'spiritualitas'),

-- 3) Buku Akademik dan Pendidikan
('Buku Akademik', 'buku-akademik'),
('Buku teks', 'buku-teks'),
('Modul pembelajaran', 'modul-pembelajaran'),
('Referensi akademik', 'referensi-akademik'),
('Monograf', 'monograf'),
('Prosiding', 'prosiding'),
('Skripsi', 'skripsi'),
('Tesis', 'tesis'),
('Disertasi', 'disertasi'),
('Kamus', 'kamus'),
('Ensiklopedia', 'ensiklopedia'),
('Atlas', 'atlas'),
('Buku latihan', 'buku-latihan'),
('Workbook', 'workbook'),
('Handbook', 'handbook'),
('Guidebook', 'guidebook'),
('Manual', 'manual'),

-- 4) Buku Anak
('Buku Anak', 'buku-anak'),
('Buku cerita anak', 'buku-cerita-anak'),
('Buku bergambar', 'buku-bergambar'),
('Buku dongeng', 'buku-dongeng'),
('Buku aktivitas', 'buku-aktivitas'),
('Buku mewarnai', 'buku-mewarnai'),
('Buku belajar membaca', 'buku-belajar-membaca'),
('Buku edukasi anak', 'buku-edukasi-anak'),
('Buku bedtime story', 'buku-bedtime-story'),
('Picture book', 'picture-book'),

-- 5) Komik dan Grafis
('Komik', 'komik'),
('Manga', 'manga'),
('Manhwa', 'manhwa'),
('Manhua', 'manhua'),
('Graphic novel', 'graphic-novel'),
('Webtoon', 'webtoon'),
('Comic strip', 'comic-strip'),
('Novel grafis edukatif', 'novel-grafis-edukatif'),
('Komik superhero', 'komik-superhero'),
('Komik humor', 'komik-humor'),

-- 6) Buku Agama dan Spiritual
('Buku Agama', 'buku-agama'),
('Alkitab', 'alkitab'),
('Kitab suci', 'kitab-suci'),
('Tafsir', 'tafsir'),
('Hadis', 'hadis'),
('Fikih', 'fikih'),
('Sejarah agama', 'sejarah-agama'),
('Renungan', 'renungan'),
('Doa-doa', 'doa-doa'),
('Spiritualitas', 'spiritualitas'),
('Tasawuf', 'tasawuf'),
('Teologi', 'teologi'),
('Buku moral', 'buku-moral'),

-- 7) Buku Referensi
('Buku Referensi', 'buku-referensi'),
('Kamus', 'kamus-umum'),
('Ensiklopedia', 'ensiklopedia-umum'),
('Tesaurus', 'tesaurus'),
('Direktori', 'direktori'),
('Almanak', 'almanak'),
('Atlas', 'atlas-umum'),
('Buku statistik', 'buku-statistik'),
('Handbook', 'handbook-umum'),
('Manual teknis', 'manual-teknis'),
('Pedoman', 'pedoman'),

-- 8) Buku Hobi dan Gaya Hidup
('Buku Hobi', 'buku-hobi'),
('Berkebun', 'berkebun'),
('Kerajinan tangan', 'kerajinan-tangan'),
('DIY', 'diy'),
('Menjahit', 'menjahit'),
('Memasak', 'memasak'),
('Memancing', 'memancing'),
('Olahraga', 'olahraga'),
('Musik', 'musik'),
('Game', 'game'),
('Koleksi', 'koleksi'),
('Seni rupa', 'seni-rupa'),
('Desain interior', 'desain-interior'),
('Fashion', 'fashion'),
('Lifestyle', 'lifestyle'),

-- 9) Buku Profesional
('Buku Profesional', 'buku-profesional'),
('Hukum', 'hukum-profesional'),
('Kedokteran', 'kedokteran'),
('Keperawatan', 'keperawatan'),
('Farmasi', 'farmasi'),
('Pendidikan profesi', 'pendidikan-profesi'),
('Akuntansi', 'akuntansi'),
('Audit', 'audit'),
('Marketing', 'marketing'),
('HR', 'hr'),
('IT', 'it-profesional'),
('Engineering', 'engineering'),
('Arsitektur', 'arsitektur'),
('Arkeologi', 'arkeologi'),
('Administrasi publik', 'administrasi-publik'),

-- 10) Buku Sastra
('Buku Sastra', 'buku-sastra'),
('Novel', 'novel'),
('Cerpen', 'cerpen'),
('Novella', 'novella'),
('Puisi', 'puisi'),
('Drama', 'drama-sastra'),
('Naskah teater', 'naskah-teater'),
('Prosa', 'prosa'),
('Kumpulan esai sastra', 'kumpulan-esai-sastra'),
('Kumpulan cerpen', 'kumpulan-cerpen'),
('Antologi puisi', 'antologi-puisi'),

-- 11) Buku Populer dan Hiburan
('Buku Populer', 'buku-populer'),
('Bestseller', 'bestseller'),
('Self-help', 'self-help'),
('Motivasi', 'motivasi-populer'),
('Inspirasi', 'inspirasi'),
('Humor', 'humor'),
('Parodi', 'parodi-hiburan'),
('Gossip', 'gossip'),
('Buku fandom', 'buku-fandom'),
('Fanfiction', 'fanfiction'),
('Buku remaja', 'buku-remaja')
ON CONFLICT (slug) DO NOTHING;
